# Generated by Django 3.0.6 on 2021-02-08 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBreadcrumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb_image', models.ImageField(default='', upload_to='blogpage/images')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Breadcrumb',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300)),
                ('blog_short_description', models.TextField()),
                ('blog_content', models.TextField()),
                ('blog_thumbnail', models.ImageField(upload_to='blogpage/images')),
                ('blog_author_description', models.TextField()),
                ('blog_added_date', models.DateTimeField(auto_now_add=True)),
                ('blog_image_1', models.ImageField(blank=True, null=True, upload_to='blogpage/images')),
                ('blog_image_2', models.ImageField(blank=True, null=True, upload_to='blogpage/images')),
                ('blog_image_3', models.ImageField(blank=True, null=True, upload_to='blogpage/images')),
                ('blog_image_4', models.ImageField(blank=True, null=True, upload_to='blogpage/images')),
                ('blog_image_5', models.ImageField(blank=True, null=True, upload_to='blogpage/images')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='RootComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor_message', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogpage.Blogs')),
                ('user', models.ForeignKey(on_delete=models.SET(1), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Root Comments',
            },
        ),
        migrations.CreateModel(
            name='ReplyComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor_message', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('root_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogpage.RootComments')),
                ('user', models.ForeignKey(on_delete=models.SET(1), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reply Comments',
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogpage.Categories'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_tag',
            field=models.ManyToManyField(to='Blogpage.Tags'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='user',
            field=models.OneToOneField(on_delete=models.SET(1), to=settings.AUTH_USER_MODEL),
        ),
    ]
