# Generated by Django 3.0.6 on 2021-02-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBreadcrumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb_image', models.ImageField(default='', upload_to='aboutpage/images')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Breadcrumb',
            },
        ),
        migrations.CreateModel(
            name='HitTechSolutionGroupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('paragraph', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='aboutpage/images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='aboutpage/images')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='aboutpage/images')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='aboutpage/images')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='aboutpage/images')),
            ],
            options={
                'verbose_name_plural': 'Hit Tech Solution Group History',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('label', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Statistics',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='StatisticSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('paragraraph', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='aboutpage/images')),
            ],
            options={
                'verbose_name_plural': 'Statistic Section',
            },
        ),
    ]
