# Generated by Django 3.0.6 on 2021-02-13 17:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbreadcrumb',
            name='breadcrumb_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='aboutpage/images'),
        ),
        migrations.AlterField(
            model_name='hittechsolutiongrouphistory',
            name='image_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aboutpage/images'),
        ),
        migrations.AlterField(
            model_name='hittechsolutiongrouphistory',
            name='image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aboutpage/images'),
        ),
        migrations.AlterField(
            model_name='hittechsolutiongrouphistory',
            name='image_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aboutpage/images'),
        ),
        migrations.AlterField(
            model_name='hittechsolutiongrouphistory',
            name='image_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aboutpage/images'),
        ),
        migrations.AlterField(
            model_name='hittechsolutiongrouphistory',
            name='image_5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aboutpage/images'),
        ),
        migrations.AlterField(
            model_name='statisticsection',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aboutpage/images'),
        ),
    ]
