# Generated by Django 3.0.6 on 2021-02-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBreadcrumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb_image', models.ImageField(upload_to='contactpage/images')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Breadcrumb',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contact Form',
            },
        ),
    ]
