# Generated by Django 3.0.6 on 2021-02-13 17:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contactpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbreadcrumb',
            name='breadcrumb_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='contactpage/images'),
        ),
    ]
