# Generated by Django 3.0.6 on 2021-02-08 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/images')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Footer Gallery',
            },
        ),
        migrations.CreateModel(
            name='HomeBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='homepage/images')),
                ('background_title', models.CharField(max_length=100)),
                ('background_description_paragraph', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Home Backgrounds',
            },
        ),
        migrations.CreateModel(
            name='HomeDisplayServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_flaticon_class', models.CharField(max_length=100)),
                ('service_title', models.CharField(max_length=40)),
                ('service_description_paragraph', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Home Display Services',
            },
        ),
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_heading', models.CharField(max_length=100)),
                ('testimonial_description_paragraph', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Testimonial Section',
            },
        ),
        migrations.CreateModel(
            name='TestimonyAddingSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony_section_heading', models.CharField(max_length=100)),
                ('testimonial_background', models.ImageField(upload_to='homepage/images')),
                ('testimony_section_description_paragraph', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Testimony Adding Section',
            },
        ),
        migrations.CreateModel(
            name='WhatWeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=50)),
                ('offer_flaticon_class', models.CharField(max_length=20)),
                ('offer_description', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'What We Offer',
            },
        ),
        migrations.CreateModel(
            name='WhatWeOfferSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_heading', models.CharField(max_length=30)),
                ('section_description_paragraph', models.TextField()),
                ('section_aside_image', models.ImageField(upload_to='homepage/images')),
            ],
            options={
                'verbose_name_plural': 'What We Offer Section',
            },
        ),
        migrations.CreateModel(
            name='TestimonyAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Testimony Authors',
            },
        ),
    ]
