# Generated by Django 3.0.6 on 2021-02-13 17:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footergallery',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='homepage/images'),
        ),
        migrations.AlterField(
            model_name='homebackground',
            name='background_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='homepage/images'),
        ),
        migrations.AlterField(
            model_name='testimonyaddingsection',
            name='testimonial_background',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='homepage/images'),
        ),
        migrations.AlterField(
            model_name='whatweoffersection',
            name='section_aside_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='homepage/images'),
        ),
    ]
