# Generated by Django 3.0.6 on 2021-02-08 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberBreadcrumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb_image', models.ImageField(default='', upload_to='memberspage/images')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Breadcrumb',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_position', models.CharField(blank=True, max_length=60, null=True)),
                ('member_country', models.CharField(blank=True, max_length=60, null=True)),
                ('member_city', models.CharField(blank=True, max_length=60, null=True)),
                ('member_image', models.ImageField(blank=True, null=True, upload_to='memberspage/images')),
                ('about_member', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='StaffMembersSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_heading', models.CharField(max_length=50)),
                ('section_paragraph_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Staff members section',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaForStaffUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_username', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_username', models.CharField(blank=True, max_length=100, null=True)),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_username', models.CharField(blank=True, max_length=100, null=True)),
                ('dribble_username', models.CharField(blank=True, max_length=100, null=True)),
                ('stack_overflow_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Memberspage.Members')),
            ],
            options={
                'verbose_name_plural': 'Social media for staff users',
            },
        ),
    ]
